# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Learning Leadership
email: simon.balderson@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Exploring leadership and life in the world of education. Hosted by Simon Balderson and Stuart Elks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://learningleadership.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SimonWBalderson
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

podcast_url: https://learningleadership.net
podcast_album_art: /images/learning-leadership-coverart1-large.jpg
podcast_title: Learning Leadership
podcast_owner: Simon Balderson
podcast_email: simon.balderson@gmail.com
podcast_category: "Education"
podcast_subcategory_one: "Training"
podcast_subcategory_two: "K-12"
podcast_explicit: "no"
podcast_author: Simon Balderson and Stuart Elks
podcast_description: Exploring leadership and life in the world of education. Hosted by Simon Balderson and Stuart Elks.
podcast_summary: Simon Balderson and Stuart Elks discuss practical ways to improve your leadership in an educational environment, no matter how long you have been in teaching.
podcast_subtitle: Exploring leadership and life in the world of education. Hosted by Simon Balderson and Stuart Elks.
